[uat_webservers]
  172.31.12.11 ansible_ssh_user='ec2-user' ansible_ssh_private_key_file=/home/ubuntu/.ssh/A4L.pem
  172.31.1.140 ansible_ssh_user='ec2-user' ansible_ssh_private_key_file=/home/ubuntu/.ssh/A4L.pem